[package]
name = "nightcycle/sky-service"
description = "A package!"
version = "1.0.0"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
ColdFusion = "nightcycle/cold-fusion@9.0.7"
GeometryUtil = "nightcycle/geometry-util@1.1.1"
Maid = "nightcycle/maid@1.1.4"
ServiceProxy = "nightcycle/service-proxy@1.0.0"
Signal = "nightcycle/signal@1.0.2"
CurveUtil = "nightcycle/curve-util@1.0.0"
InstancePool = "nightcycle/instance-pool@1.0.0"
